services:
  mysql1:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql1/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/mysql1/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  mysql2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql2/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/mysql2/init.sql:/docker-entrypoint-initdb.d/init.sql
